---
baseURL: https://geekdocs.de/
title: Geekdocs
theme: hugo-geekdoc

pygmentsUseClasses: true
pygmentsCodeFences: true
timeout: 180000
pluralizeListTitles: false

defaultContentLanguage: en

disablePathToLower: true
enableGitInfo: true

enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

taxonomies:
  tag: tags

outputs:
  home:
    - HTML
  page:
    - HTML
  section:
    - HTML
  taxonomy:
    - HTML
  term:
    - HTML

security:
  exec:
    allow:
      - "^asciidoctor$"

params:
  geekdocToC: 3
  geekdocTagsToMenu: true

  geekdocRepo: https://github.com/thegeeklab/hugo-geekdoc123
  geekdocEditPath: edit/main/exampleSite

  geekdocSearch: true
  geekdocSearchShowParent: true

  geekdocLegalNotice: https://thegeeklab.de/legal-notice/#contact-information
  geekdocPrivacyPolicy: https://thegeeklab.de/legal-notice/#privacy-policy

  geekdocImageLazyLoading: true
  geekdocDarkModeDim: true