---
baseURL: https://docs.ava.do/
title: Docs
theme: hugo-geekdoc

pygmentsUseClasses: true
pygmentsCodeFences: true
timeout: 180000
pluralizeListTitles: false

defaultContentLanguage: en

disablePathToLower: true
enableGitInfo: true

enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

taxonomies:
  tag: tags

outputs:
  home:
    - HTML
  page:
    - HTML
  section:
    - HTML
  taxonomy:
    - HTML
  term:
    - HTML

security:
  exec:
    allow:
      - "^asciidoctor$"

params:
  geekdocToC: 3
  geekdocTagsToMenu: true

  geekdocRepo: https://github.com/AvadoDServer/avado-docs
  geekdocEditPath: edit/master/

  geekdocSearch: true
  geekdocSearchShowParent: true

  geekdocNextPrev: false

  geekdocImageLazyLoading: true
  geekdocDarkModeDim: true

# https://gohugo.io/templates/internal/#google-analytics
googleAnalytics: G-LY5MPSFFD2

minify:
  disableHTML: true